version: '3.3'

services:

  db:
    image: postgres

  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./services/nginx/aenglisc.conf:/aenglisc.conf"
    depends_on:
      - app

  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: mix phx.server
    ports: 
      - "4000:4000"
    env_file: '.env'
    volumes:
      - "~/.bash-history:/.bash-history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"
    depends_on:
      - db
