FROM bitwalker/alpine-elixir-phoenix:1.6.1

ENV MIX_ENV prod

WORKDIR app
# Add the files to the image
COPY . . 

# Cache Elixir deps
RUN mix deps.get --only prod
RUN mix deps.compile

WORKDIR assets
# Cache Node deps
RUN npm i

# Compile JavaScript
RUN npm run deploy

WORKDIR ..
# Compile app
RUN mix compile
RUN mix phx.digest
